package com.similan.service.api.wall.dto.basic;

public enum WallEntryType {

  WALL_POST,

  COLLABORATION_WORKSPACE_PARTICIPANT_JOINED,

  COLLABORATION_WORKSPACE_DOCUMENT_SHARED,

  COLLABORATION_WORKSPACE_DOCUMENT_EXTERNAL_SHARED,

  COLLABORATION_WORKSPACE_DOCUMENT_INNETWORK_SHARED,

  COLLABORATION_WORKSPACE_TASK_CREATED,

  COLLABORATION_WORKSPACE_DOCUMENT_DOWNLOADED,

  COLLABORATION_WORKSPACE_DOCUMENT_VIEWED,

  COLLABORATION_WORKSPACE_DOCUMENT_UPDATED,

  COLLABORATION_WORKSPACE_DOCUMENT_COMMENT,
  
  COLLABORATION_WORKSPACE_DOCUMENT_UNSHARED,

  COLLABORATION_WORKSPACE_DOCUMENT_SHARED_ANOTHER_WORKSPACE,

  COLLABORATION_WORKSPACE_ACCESSED,

  NEWS_POST_WALL_ENTRY,

  COMMENT_POSTED,

  COMMENT_REPLY_POSTED,

  MEMBER_PROFILE_VIEWED,

  MEMBER_PROFILE_UPDATED,

  BUSINESS_PROFILE_VIEWED,

  BUSINESS_PROFILE_UPDATED,

  PARTNER_PROGRAM_UPDATED,

  CONTENT_WORKSPACE_DOCUMENT_VIEWED,

  CONTENT_WORKSPACE_DOCUMENT_UPDATED,

  CONTENT_WORKSPACE_DOCUMENT_DOWNLOADED,

  CONTENT_WORKSPACE_DOCUMENT_UPLOADED,

  CONTENT_WORKSPACE_DOCUMENT_SHARED,

  CONTENT_WORKSPACE_DOCUMENT_EXTERNAL_SHARED,

  CONTENT_WORKSPACE_DOCUMENT_INNETWORK_SHARED,

  CONTENT_WORKSPACE_DOCUMENT_COMMENT,

  CONTENT_WORKSPACE_DOCUMENT_CHECKOUT,

  CONTENT_WORKSPACE_DOCUMENT_CHECKIN,

  CONTENT_WORKSPACE_DOCUMENT_DELETE,

  CONTENT_WORKSPACE_PARTICIPANT_JOINED,

  PARTNER_JOINED,

  DISPLAY_NOTICE_VIEWED

  ;
}
